apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dynamic-auth
  namespace: db-demo
spec:
  namespace: master-demo
  method: kubernetes
  mount: master-demo-auth
  kubernetes:
    role: master-demo-auth-role
    serviceAccount: demo-dynamic-app
    audiences:
      - vault

# Made with Bob
