apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: encryption-db-creds
  namespace: encryption-demo
spec:
  type: kv-v2
  mount: master-demo-kv
  path: encryption-db-creds
  namespace: master-demo
  destination:
    name: encryption-db-creds
    create: true
  refreshAfter: 30s
  vaultAuthRef: encryption-auth

# Made with Bob