defaultVaultConnection:
  enabled: true
  # Use host.minikube.internal to access host machine from minikube
  address: "https://host.minikube.internal:8200"
  skipTLSVerify: true

controller:
  kubeRbacProxy:
    enabled: false
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: master-demo-auth
        keyName: vso-client-cache
        namespace: "master-demo"
        transitMount: master-demo-transit
        kubernetes:
          role: master-demo-auth-role-operator
          serviceAccount: vault-secrets-operator-controller-manager
          tokenAudiences: ["vault"]
