apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-kv-secret
  namespace: gitlab-demo
spec:
  type: kv-v2
  namespace: master-demo
  mount: master-demo-kv
  path: webapp/config
  destination:
    name: secretkv
    create: true
  refreshAfter: 30s
  vaultAuthRef: gitlab-auth

# Made with Bob