apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-demo
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: gitlab-auth
  namespace: gitlab-demo
spec:
  namespace: master-demo
  method: kubernetes
  mount: master-demo-auth
  kubernetes:
    role: master-demo-gitlab-role
    serviceAccount: gitlab-runner
    audiences:
      - vault
# Made with Bob