apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: pki-demo-cert
  namespace: pki-demo
spec:
  namespace: master-demo
  mount: master-demo-pki-issuing
  role: master-demo-cert-issuer
  commonName: demo.local
  format: pem
  revoke: true
  clear: true
  expiryOffset: 5s
  ttl: 30s
  altNames:
    - "*.demo.local"
    - "pki-demo-app.pki-demo.svc.cluster.local"
  destination:
    create: true
    name: pki-demo-tls
  vaultAuthRef: pki-auth
# Made with Bob